### ISSUE TITLE
Ability to paste in full SoundCloud URL

### ISSUE THREAD

**Issue by rtsao** [L33T-KR3W/soundcasts-web#1]
We should allow users to paste in a full SoundCloud URL which we should automatically convert to just the profile. For example:

`https://soundcloud.com/duskymusic` -> `duskymusic`

See: https://github.com/L33T-KR3W/soundcasts-server/issues/10

**Comment by mmedal** [comment]
one size fits all input box? like, just the username is chill, or username is stripped from a url is provided?
