### ISSUE TITLE
Styles Refactoring

### ISSUE THREAD

**Issue by scott113341** [L33T-KR3W/soundcasts-web#6]
https://github.com/rtsao/csjs

Our goal should be to have ZERO non-JavaScript stuff in this repo

**Comment by rtsao** [comment]
- [x] Use normalize.css instead of reset.css
- [x] Optimize rules (only class selectors, no wildcard selectors or descendent combinators, etc.)
- [x] DRY it up (Autoprefixing, etc.)
- [x] Use pure inline styles or CSJS?

**Comment by scott113341** [comment]
CSJS plz
